[
	{ "id":1, "descripK":"내가 이해하는 모든 것은 내가 사랑하기 때문에 이해한다.", "authK":"레프 톨스토이", 
		"descripE":"Everything that I understand, I understand only because I love.", "authE":"Lev Tolstoy", "category":"love" },
	{ "id":2, "descripK":"사랑은 모두가 기대하는 것이다. 사랑은 진정 싸우고, 용기를 내고, 모든 것을 걸 만하다.", "authK":"에리카 종",
		"descripE":"Love is everything it's cracked up to be. It really is worth fighting for, being brave for, risking everything for.", "authE":"Erica Jong", "category":"love"},
	{ "id":3, "descripK":"사랑에 의해 행해지는 것은 언제나 선악을 초월한다.", "authK":"프레드리히 나체",
		"descripE":"What is done out of love always takes place beyond good and evil.", "authE":"Friedrich Nietzsche", "category":"love"},
	{ "id":4, "descripK":"겁쟁이는 사랑을 드러낼 능력이 없다. 사랑은 용기있는 자의 특권이다.", "authK":"마하트마 간디",
		"descripE":"A coward is incapable of exhibiting love, it is the prerogative of the brave.", "authE":"Mahatma Gandhi", "category":"love"},
	{ "id":5, "descripK":"사랑은 눈으로 보지 않고 마음으로 보는 거지.", "authK":"윌리엄 셰익스피어",
		"descripE":"Love looks not with the eyes, but with the mind.", "authE":"William Shakespeare", "category":"love"},
	{ "id":6, "descripK":"나는 젊음이요, 나는 기쁨이요, 나는 알에서 갓 깬 작은 새다.", "authK":"제임스 M. 배리",
		"descripE":"I'm youth, I'm joy, I'm a little bird that has broken out of the egg.", "authE":"James M. Barrie", "category":"life"},
	{ "id":7, "descripK":"어진 사람을 보면 그와 같이 되기를 생각하고, 어질지 않은 사람을 보면 속으로 스스로 반성하라.", "authK":"공자",
		"descripE":"When we see men of worth, we should think of equaling them; when we see men of a contrary character, we should turn inwards and examine ourselves.", "authE":"Confucius", "category":"life"},
	{ "id":8, "descripK":"인간사에는 안정된 것이 하나도 없음을 기억하라. 그러므로 성공에 들뜨거나 역경에 지나치게 의기소침하지 마라.", "authK":"소크라테스",
		"descripE":"Remember that there is nothing stable in human affairs; therefore avoid undue elation in prosperity, or undue depression in adversity.", "authE":"Socrates", "category":"life"},
	{ "id":9, "descripK":"자기 새끼를 잡아먹기 좋아하는 담수어를 제외하고 인간은 일부러 아이를 가지는 유일한 동물이다.", "authK":"P. J. 오루크",
		"descripE":"Humans are the only animals that have children on purpose with the exception of guppies, who like to eat theirs.", "authE":"P. J. O'Rourke", "category":"life"},
	{ "id":10, "descripK":"진정한 여행자는 걸어서 다니는 자이며, 걸으면서도 자주 앉는다.", "authK":"콜레트",
		"descripE":"The true traveler is he who goes on foot, and even then, he sits down a lot of the time", "authE":"Colette", "category":"life"},
	{ "id":11, "descripK":"제대로 배우기 위해서는 거창하고 교양 있는 전통이나 돈이 필요하지 않다. 스스로를 개선하고자 하는 열망이 있는 사람들이 필요할 뿐이다.", "authK":"아담 쿠퍼",
		"descripE":"You don't need fancy highbrow traditions or money to really learn. You just need people with the desire to better themselves.", "authE":"Adam Cooper", "category":"study"},
	{ "id":12, "descripK":"어려운 직업에서 성공하려면 자신을 굳게 믿어야 한다. 이것이 탁월한 재능을 지닌 사람보다 재능은 평범하지만 강한 투지를 가진 사람이 훨씬 더 성공하는 이유다.", "authK":"소피아 로렌",
		"descripE":"Getting ahead in a difficult profession requires avid faith in yourself. That is why some people with mediocre talent, but with great inner drive, go much further than people with vastly superior talent.", "authE":"Sophia Loren", "category":"study"},
	{ "id":13, "descripK":"아이들이 답이 있는 질문을 하기 시작하면 그들이 성장하고 있음을 알 수 있다.", "authK":"존 J. 플롬프",
		"descripE":"You know that children are growing up when they start asking questions that have answers.", "authE":"John J. Plomp", "category":"study"},
	{ "id":14, "descripK":"인생에서 가장 위대한 교훈은, 심지어는 바보도 어떨 때는 옳다는 걸 아는 것이다.", "authK":"윈스턴 처칠",
		"descripE":"The greatest lesson in life is to know that even fools are right sometimes.", "authE":"Sir Winston Churchill", "category":"study"},
	{ "id":15, "descripK":"함께 있는 사람들보다 학식이 높아 보이지 말라. 당신의 학식을 회중시계마냥 주머니 속에 감춰라. 단지 시간을 세기 위해 시계를 꺼내지 말되 누군가가 시간을 물어보면 알려줘라.", "authK":"체스터필드 경",
		"descripE":"Never seem more learned than the people you are with. Wear your learning like a pocket watch and keep it hidden. Do not pull it out to count the hours, but give the time when you are asked.", "authE":"Lord Chesterfield", "category":"study"},
	{ "id":16, "descripK":"인간은 운명의 포로가 아니라 단지 자기 마음의 포로일 뿐이다.", "authK":"프랭클린 D. 루스벨트",
		"descripE":"Men are not prisoners of fate, but only prisoners of their own minds.", "authE":"Franklin D. Roosevelt", "category":"success"},
	{ "id":17, "descripK":"새로운 것의 창조는 지능이 아니라 내적 필요에 의한 놀기 본능을 통해 달성된다. 창의적인 사람은 자신이 사랑하는 것을 가지고 놀기 좋아한다.", "authK":"칼 융",
		"descripE":"The creation of something new is not accomplished by the intellect but by the play instinct acting from inner necessity. The creative mind plays with the objects it loves.", "authE":"Carl Jung", "category":"success"},
	{ "id":18, "descripK":"기회가 찾아오는 정확한 때와 장소를 알아보고 그 기회를 잡을 수 있어야 한다. 세상에 기회는 많다. 그저 손 놓고 앉아 있을 수는 없다.", "authK":"엘렌 멧칼프",
		"descripE":"You have to recognize when the right place and the right time fuse and take advantage of that opportunity. There are plenty of opportunities out there. You can't sit back and wait.", "authE":"Ellen Metcalf", "category":"success"},
	{ "id":19, "descripK":"우리가 어떤 형태로든 '될대로 되라지!'라고 할 때 마다 무슨 일이 생긴다.", "authK":"스텔라 테릴 만",
		"descripE":"Every time we say, 'Let there be!' in any form, something happens.", "authE":"Stella Terrill Mann", "category":"success"},
	{ "id":20, "descripK":"남에게 이기는 방법의 하나는 예의범절로 이기는 것이다.", "authK":"조쉬 빌링스",
		"descripE":"One of the greatest victories you can gain over someone is to beat him at politeness.", "authE":"Josh Billings", "category":"success"},
	{ "id":21, "descripK":"친구라면 친구의 결점을 참고 견뎌야 한다.", "authK":"윌리엄 셰익스피어",
		"descripE":"A friend should bear his friend's infirmities.", "authE":"William Shakespeare", "category":"friend"},
	{ "id":22, "descripK":"친구는 모든 것을 나눈다.", "authK":"플라톤",
		"descripE":"Friends have all things in common.", "authE":"Plato", "category":"friend"},
	{ "id":23, "descripK":"친구의 충고는 신중하게 곱씹어 받아들여야 한다. 옳건 그르건, 자신의 생각을 포기하고 친구의 충고를 무조건 따라서는 안된다.", "authK":"피에르 샤롱",
		"descripE":"The advice of friends must be received with a judicious reserve, we must not give ourselves up to it and follow it blindly, whether right or wrong.", "authE":"Pierre Charron", "category":"friend"},
	{ "id":24, "descripK":"아첨꾼은 나보다 열등하거나 그런 척 하는 친구이다.", "authK":"아리스토텔레스",
		"descripE":"A flatterer is a friend who is your inferior, or pretends to be so.", "authE":"Aristotle", "category":"friend"},
	{ "id":25, "descripK":"운명의 기복은 친구의 신뢰를 시험한다.", "authK":"키케로",
		"descripE":"The shifts of Fortune test the reliability of friends.", "authE":"Cicero", "category":"friend"},
	{ "id":26, "descripK":"좋은 책을 읽는 것은 과거 몇 세기의 가장 훌륭한 사람들과 이야기를 나누는 것과 같다.", "authK":"르네 데카르트",
		"descripE":"The reading of all good books is like a conversation with the finest men of past centuries.", "authE":"Rene Descartes", "category":"study"},
	{ "id":27, "descripK":"읽는 것 만큼 쓰는 것을 통해서도 많이 배운다.", "authK":"액톤 경",
		"descripE":"Learn as much by writing as by reading.", "authE":"Lord Acton", "category":"study"},
	{ "id":28, "descripK":"부당하게 잊혀지는 책은 있어도 과분하게 기억되는 책은 없다.", "authK":"오든",
		"descripE":"Some books are undeservedly forgotten, none are undeservedly remembered.", "authE":"W. H. Auden", "category":"study"},
	{ "id":29, "descripK":"낡은 외투를 그냥 입고 새 책을 사라.", "authK":"오스틴 펠프스",
		"descripE":"Wear the old coat and buy the new book.", "authE":"Austin Phelps", "category":"study"},
	{ "id":30, "descripK":"나는 삶을 변화시키는 아이디어를 항상 책에서 얻었다.", "authK":"벨 훅스",
		"descripE":"Life-transforming ideas have always come to me through books.", "authE":"Bell Hooks", "category":"study"},
	{ "id":31, "descripK":"실제로 느끼지 못하는 사랑을 느끼는 척 하지 말라. 사랑은 우리가 좌지우지 할 수 없으므로", "authK":"앨런 왓츠", 
		"descripE": "Never pretend to a love which you do not actually feel, for love is not ours to command.", "authE":"Alan Watts", "category":"love"},
	{ "id":32, "descripK":"인생에 있어서 최고의 행복은 우리가 사랑받고 있음을 확신하는 것이다.", "authK":"빅터 위고", 
		"descripE":"Life's greatest happiness is to be convinced we are loved.", "authE":"Victor Hugo", "category":"love"},
	{ "id":33, "descripK":"세기의 사랑일지라도 참고 견뎌내야 한다.", "authK":"가브리엘(코코)샤넬", 
		"descripE":"Great loves too must be endured.", "authE":"Gabriel Coco Chanel", "category":"love"},
	{ "id":34, "descripK":"사랑의 첫 번째 의무는 상대방에 귀기울이는 것이다.", "authK": "폴 틸리히", 
		"descripE":"The first duty of love is to listen.", "authE":"Paul Tillich", "category":"love"},
	{ "id":35, "descripK":"용기있다는 것은 답례로 아무것도 기대하지 않고 누군가를 무조건적으로 사랑하는 것이다. 사랑을 그저 주는 것이다. 우리는 넘어지거나 쉽게 상처 받길 원치 않으므로 사랑하려면 용기가 필요하다", "authK":"마돈나", 
		"descripE":"To be brave is to love someone unconditionally, without expecting anything in return. To just give. That takes courage, because we don't want to fall on our faces or leave ourselves open to hurt.", "authE":"Madonna", "category":"love"},
	{ "id":36, "descripK":"정신이 명료함은 열정도 명료함을 뜻한다. 때문에 위대하고 명료한 정신을 지닌 자는 열정적으로 사랑하고 자신이 사랑하는 대상을 분명히 안다", "authK":"블레이즈 파스칼", 
		"descripE":"Clarity of mind means clarity of passion, too; this is why a great and clear mind loves ardently and sees distinctly what it loves.", "authE":"Blaise Pascal", "category":"love"},
	{ "id":37, "descripK":"행복한 결혼 생활에서 중요한 것은 서로 얼마나 잘 맞는가보다 다른 점을 어떻게 극복해나가는가이다.", "authK":"레프 톨스토이", 
		"descripE":"What counts in making a happy marriage is not so much how compatible you are, but how you deal with incompatibility.", "authE":"Lev Tolstoy", "category":"love"},
	{ "id":38, "descripK":"사랑이란 서로 마주보는 것이 아니라 둘이서 똑같은 방향을 내다보는 것이라고 인생은 우리에게 가르쳐 주었다.", "authK":"생텍쥐페리", 
		"descripE":"Love has taught us that love does not consist in gazing at each other but in looking outward together in the same direction.", "authE":"Antoine de Saint-Exupery", "category":"love"},
	{ "id":39, "descripK":"20대에 당신의 얼굴은 자연이 준 것이지만, 50대의 당신의 얼굴은 스스로 가치를 만들어야 한다.", "authK":"가브리엘(코코)샤넬", 
		"descripE":"Nature gives you the face you have at twenty; it is up to you to merit the face you have at fifty.", "authE":"Gabriel Coco Chanel", "category":"life"},
	{ "id":40, "descripK":"우리는 나이가 들면서 변하는 게 아니다. 보다 자기다워지는 것이다.", "authK":"린 홀", 
		"descripE":"We did not change as we grew older; we just became more clearly ourselves.", "authE":"Lynn Hall", "category":"life"},
	{ "id":41, "descripK":"안전이란 대개 미신이다. 그것은 사실상 존재하지 않는다… 인생은 대담한 모험이거나 아니면 아무것도 아니다.", "authK":"헬렌 켈러", 
		"descripE":"Security is mostly a superstition. It does not exist in nature.... Life is either a daring adventure or nothing.", "authE":"Helen Keller", "category":"life"},
	{ "id":42, "descripK":"우리는 젊을 때에 배우고 나이가 들어서 이해한다.", "authK":"마리 폰 에브너 에셴바흐", 
		"descripE":"In youth we learn; in age we understand.", "authE":"Marie Ebner von Eschenbach", "category":"life"},
	{ "id":43, "descripK":"결코 눈덩이를 던져보고 싶은 충동이 생기지 않으면, 당신은 노화의 손아귀에 꽉 붙잡힌 것이다.", "authK":"더그 라슨", 
		"descripE":"The aging process has you firmly in its grasp if you never get the urge to throw a snowball.", "authE":"Doug Larson", "category":"life"},
	{ "id":44, "descripK":"인격은 그 사람의 운명이다.", "authK":"헤라클레이토스", 
		"descripE": "A man's character is his fate.", "authE":"Heraclitus", "category":"life"},
	{ "id":45, "descripK":"인생에서 원하는 것을 얻기 위한 첫 번째 단계는 내가 무엇을 원하는지 결정하는 것이다", "authK": "벤 스타인", 
		"descripE": "The first step to getting the things you want out of life is this: Decide what you want.", "authE":"Ben Stein", "category":"life"},
	{ "id":46, "descripK":"교육은 최상의 노후 대비책이다.", "authK":"아리스토텔레스", 
		"descripE":"Education is the best provision for old age.", "authE":"Aristotle", "category":"study"},
	{ "id":47, "descripK":"배움이 없는 자유는 언제나 위험하며 자유가 없는 배움은 언제나 헛된 일입니다.", "authK":"존 F. 케네디", 
		"descripE":"Liberty without learning is always in peril; learning without liberty is always in vain.", "authE":"John F. Kennedy", "category":"study"},
	{ "id":48, "descripK":"배우기만 하고 생각하지 않으면 얻는 것이 없고, 생각만 하고 배우지 않으면 위태롭다.", "authK":"공자", 
		"descripE":"He who learns but does not think, is lost! He who thinks but does not learn is in great danger.", "authE":"Confucius", "category":"study"},
	{ "id":49, "descripK":"행동만이 삶에 힘을 주고, 절제만이 삶에 매력을 준다.", "authK":"장 폴 리히터", 
		"descripE":"Only actions give life strength; only moderation gives it a charm.", "authE":"Jean Paul Richter", "category":"study"},
	{ "id":50, "descripK":"한 사람에게서 모든 덕을 구하지 말라.", "authK":"공자", 
		"descripE":"Seek not every quality in one individual.", "authE":"Confucius", "category":"study"},
	{ "id":51, "descripK":"명성을 쌓는 데는 20년이란 세월이 걸리며, 명성을 무너뜨리는 데는 채 5분도 걸리지 않는다. 그걸 명심한다면, 당신의 행동이 달라질 것이다.", "authK":"워런 버핏", 
		"descripE":"It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you'll do things differently.", "authE":"Warren Buffett", "category":"study", "kinda":"c"},
	{ "id":52, "descripK":"내가 농부들과 함께 있는 것을 더 좋아하는 이유는 농부들은 잘못 사고하도록 충분한 교육을 받지 않았기 때문이다.", "authK":"미셸 드 몽테뉴", 
		"descripE":"I prefer the company of peasants because they have not been educated sufficiently to reason incorrectly.", "authE":"Michel de Montaigne", "category":"study"},
	{ "id":53, "descripK":"인생에 있는 큰 비밀은 큰 비밀 따위는 없다는 것이다. 당신의 목표가 무엇이든 열심히 할 의지가 있다면 달성할 수 있다.", "authK":"오프라 윈프리", 
		"descripE":"The big secret in life is that there is no big secret. Whatever your goal, you can get there if you're willing to work.", "authE":"Oprah Winfrey", "category":"success", "kinda":"c"},
	{ "id":54, "descripK":"성공의 8할은 일단 출석하는 것이다.", "authK":"우디 알렌", 
		"descripE":"Eighty percent of success is showing up.", "authE":"Woody Allen", "category":"success"},
	{ "id":55, "descripK":"의심으로 가득 찬 마음은 승리로의 여정에 집중할 수 없다.", "authK":"아서 골든", 
		"descripE":"A mind troubled by doubt cannot focus on the course to victory.", "authE":"Arthur Golden", "category":"success"},
	{ "id":56, "descripK":"저는 미래가 어떻게 전개될지는 모르지만, 누가 그 미래를 결정하는지는 압니다.", "authK": "오프라 윈프리", 
		"descripE":"I do not know what the future holds, but I know who holds the future.", "authE":"Oprah Winfrey", "category":"success", "kinda":"c"},
	{ "id":57, "descripK":"자신의 능력을 감추지 마라. 재능은 쓰라고 주어진 것이다. 그늘 속의 해시계가 무슨 소용이랴.", "authK":"벤자민 프랭클린", 
		"descripE":"Hide not your talents. They for use were made. What's a sundial in the shade.", "authE":"Benjamin Franklin", "category":"confidence"},
	{ "id":58, "descripK":"우리가 이룬 것만큼, 이루지 못한 것도 자랑스럽습니다.", "authK":"스티브 잡스", 
		"descripE":"I'm as proud of what we don't do as I am of what we do.", "authE":"Steve Jobs", "category":"confidence", "kinda":"c"},
	{ "id":59, "descripK":"제프, 누구요?", "authK":"일론 머스크", 
		"descripE":"Jeff Who?", "authE":"Elon Musk", "category":"confidence", "kinda":"c"},
	{ "id":60, "descripK":"어떤 일을 달성하기로 결심했으면 그 어떤 지겨움과 혐오감도 불사하고 완수하라. 고단한 일을 해낸 데서 오는 자신감은 실로 엄청나다.", "authK":"아놀드 베넷", 
		"descripE":"Having once decided to achieve a certain task, achieve it at all costs of tedium and distaste. The gain in self-confidence of having accomplished a tiresome labor is immense.", "authE":"Arnold Bennett", "category":"confidence"},
	{ "id":61, "descripK":"자신의 능력을 믿어야 한다. 그리고 끝까지 굳세게 밀고 나가라.", "authK":"로잘린 카터", 
		"descripE":"You have to have confidence in your ability, and then be tough enough to follow through.", "authE":"Rosalynn Carter", "category":"confidence"},
	{ "id":62, "descripK":"자존이야말로 모든 미덕의 초석이다.", "authK":"존 허셀", 
		"descripE":"Self-respect is the cornerstone of all virtue.", "authE":"John Herschel", "category":"confidence"},
	{ "id":63, "descripK":"내 자신에 대한 자신감을 잃으면, 온 세상이 나의 적이 된다.", "authK":"랄프 왈도 에머슨", 
		"descripE":"If I have lost confidence in myself, I have the universe against me.", "authE":"Ralph Waldo Emerson", "category":"confidence"},
	{ "id":64, "descripK":"청년기의 자존심은 혈기와 아름다움에 있지만, 노년기의 자존심은 분별력에 있다.", "authK":"데모크리토스", 
		"descripE":"The pride of youth is in strength and beauty, the pride of old age is in discretion.", "authE":"Democritus", "category":"confidence"},
	{ "id":65, "descripK":"스스로를 경멸하는 사람은 경멸하는 자신을 존중한다.", "authK":"프레드리히 니체", 
		"descripE":"He who despises himself, respects himself as one who despises.", "authE":"Friedrich Nietzsche", "category":"confidence"},
	{ "id":66, "descripK":"꽃은 옆에 있는 꽃과 경쟁할 생각을 하지 않는다. 그저 피어나기만 한다", "authK":"zen shin", 
		"descripE":"A flower does not think of competing to the flower next to it. it just blooms", "authE":"zen shin", "category":"confidence"},
	{ "id":67, "descripK":"손으로 생각하라!", "authK":"팀 브라운, 디자인 회사 IDEO CEO", 
		"descripE":"Think with your hands!", "authE":"Tim Brown", "category":"business"},
	{ "id":68, "descripK":"이길 수 없다면 규칙을 바꿔라", "authK":"피터 디아만디스, 실리콘벨리 기업가", 
		"descripE":"If you can't win, change the rules", "authE":"Peter Diamandis", "category":"business"},
	{ "id":69, "descripK":"규칙을 바꿀 수 없으면, 규칙을 무시해라.", "authK": "피터 디아만디스, 실리콘벨리 기업가", 
		"descripE":"If you can't change the rules, then ignore them.", "authE":"Peter Diamandis", "category":"business"},
	{ "id":70, "descripK":"사업의 비결은 다른 사람들은 아무도 모르고 있는 무엇인가를 아는 것이다.", "authK":"아리스토틀 오나시스, 그리스 해운업자", 
		"descripE":"The secret of business is to know something that nobody else knows", "authE":"Aristotle Onassis", "category":"business"},
	{ "id":71, "descripK":"가장 하기 힘든 일은 아무 일도 안 하는 것이다.", "authK":"유대인 격언", 
		"descripE":"The hardest work is to go idle", "authE":"Jewish proverb", "category":"business"},
	{ "id":72, "descripK":"안다는 것은 전혀 중요하지 않다. 상상하는 것이 가장 중요하다.", "authK":"아나톨 프랑스", 
		"descripE":"To know is nothing at all, to imagine is everything", "authE":"Anatole France", "category":"business"},
	{ "id":73, "descripK":"용기있는 한 사람이 다수의 힘을 갖는다.", "authK":"앤드류 잭슨", 
		"descripE":"One man with courage makes a majority", "authE":"Andrew Jackson", "category":"business"},
	{ "id":74, "descripK":"만약 나에게 무언가 중요한것이 있다면 다른 사람이 원하지 않아도 해야한다", "authK":"일론 머스크", 
		"descripE":"When something is important enough, you do it even if the odds are not in your favor", "authE":"Elon Musk", "category":"business", "kinda":"c"},
	{ "id":75, "descripK":"보통 사람들은 변화를 꺼려한다. 하지만 지금이 재앙이라면 변화를 받아 드려야만 한다", "authK":"일론 머스크", 
		"descripE":"Some people don't like change, but you need to embrace change, if the alternative is disaster", "authE":"Elon Musk", "category":"business", "kinda":"c"},
	{ "id":76, "descripK":"위험 부담에 대한 여러 편견이 많은데 그래서 모든 사람들은 안전하게 살아가길 원한다", "authK":"일론 머스크", 
		"descripE":"There's a tremendous bias against taking risks. Everyone is trying to optimize their ass-covering.", "authE":"Elon Musk", "category":"business", "kinda":"c"},
	{ "id":77, "descripK":"끈기는 매우 중요합니다. 만약 누군가가 포기하도록 강요하지 않는이상 절대 포기해서는 안됩니다..", "authK":"일론 머스크", 
		"descripE":"Persistence is very important You should not give up unless you are forced to give up", "authE":"Elon Musk", "category":"business", "kinda":"c"},
	{ "id":78, "descripK":"실패는 하나의 옵션이다 만약 당신이 실패를 겪지 않는다면 충분히 혁신적이지 않았다는 증거다.", "authK":"일론 머스크", 
		"descripE":"Failure is an option here. If things are not failing, you are not innovating enough", "authE":"Elon Musk", "category":"business", "kinda":"c"},
	{ "id":79, "descripK":"한가지 최고의 조언은 어떻게 더 잘 해낼 수 있는지 끊임없이 생각하고 스스로에게 계속 질문을 던지십시오", "authK":"일론 머스크", 
		"descripE":"I think that's the single best piece of advide; constantly think about how you could be doing things better and questioning yourself.", "authE":"Elon Musk", "category":"business", "kinda":"c"},
	{ "id":80, "descripK":"최고를 위해서는 최대한 엄격해져야 한다 잘못된 점을 찾고 고쳐야 한다 특히 친구들로부터 부정적인 피드백을 받아라", "authK":"일론 머스크", 
		"descripE":"You want to be extra rigorous about making the best possible thing you can. Find everything that's wrong with it and fix it. Seek negative feedback, particularly from friends.", "authE":"Elon Musk", "category":"business", "kinda":"c"},
	{ "id":81, "descripK":"나는 문신 안한다. 벤틀리에다가 스티커 붙이는걸 본적 있냐?", "authK":"킴 카다시안", 
		"descripE":"I don't get tattoos, would you put a bumper sticker on a Bentley?", "authE":"Kim Kardashian", "category":"confidence", "kinda":"c"},
	{ "id":82, "descripK":"장사는 음식을 파는 게 아니라 자존심을 파는 거예요", "authK":"백종원", 
		"descripE":"Business isn't selling food, it's selling pride.", "authE":"JongWon Paik, Entrepreneur in korea", "category":"business"},
	{ "id":83, "descripK":"처음부터 아는 사람은 없다.", "authK":"마크 저커버그", 
		"descripE":"No one knows when they begin", "authE":"Mark Zuckerberg", "category":"study", "kinda":"c"},
	{ "id":84, "descripK":"아이디어는 처음부터 완전한 형태로 떠오르지 않는다.", "authK":"마크 저커버그", 
		"descripE":"Ideas don't come out fully formed", "authE":"Mark Zuckerberg", "category":"business", "kinda":"c"},
	{ "id":85, "descripK":"일을 하는 동안 아이디어는 보다 명확해진다, 그러니 바로 시작해야 한다.", "authK":"마크 저커버그", 
		"descripE":"They only become clear as you work on them. So you just have to get started.", "authE":"Mark Zuckerberg", "category":"business", "kinda":"c"},
	{ "id":86, "descripK":"인생은 집을 향한 여행이다.", "authK":"허먼 멜빌",
		"descripE":"Life's a voyage that's homeward bound.", "authE":"Herman Melville", "category":"life"},
	{ "id":87, "descripK":"인생은 겸손에 대한 오랜 수업이다.", "authK":"제임스 M. 배리",
		"descripE":"Life is a long lesson in humility", "authE":"James M. Barrie", "category":"life"},
	{ "id":88, "descripK":"태어나면서부터 현명한 이는 없다. ", "authK":"미겔 데 세르반데스",
		"descripE":"No man is born wise", "authE":"Miguel de Cervantes", "category":"life"},
	{ "id":89, "descripK":"나이가 성숙을 보장하지는 않는다.", "authK":"라와나 블랙웰",
		"descripE":"Age is no guarantee of maturity.", "authE":"Lawana Blackwell", "category":"life"},
	{ "id":90, "descripK":"인생이란 결코 공평하지 않다. 이 사실에 익숙해져라.", "authK":"Bill Gates",
		"descripE":"Life is not fair; get used to it.", "authE":"Bill Gates", "category":"life", "kinda":"c"},
	{ "id":91, "descripK":"나만이 내 인생을 바꿀 수 있다. 아무도 날 대신해 해줄 수 없다", "authK":"케롤 버넷",
		"descripE":"Only I can change my life. No one can do it for me.", "authE":"Carol Burnett", "category":"life"},
	{ "id":92, "descripK":"인생을 다시 산다면, 나는 똑같은 실수를 조금 더 일찍 저지를 것이다.", "authK":"탈룰라 뱅크헤드",
		"descripE":"If I had to live my life again, I'd make the same mistakes, only sooner", "authE":"Tallulah Bankhead", "category":"life"},
	{ "id":93, "descripK":"조금도 위험을 감수하지 않는 것이 인생에서 가장 위험한 일일 것이라 믿는다.", "authK":"오프라 윈프리",
		"descripE":"I believe that one of life's greatest risks is never daring to risk", "authE":"Oprah Winfrey", "category":"life", "kinda":"c"},
	{ "id":94, "descripK":"허물이 있다면, 버리기를 두려워말라.", "authK":"공자, 논어",
		"descripE":"When you have faults, do not fear to abandon them.", "authE":"Confucius", "category":"life"},
	{ "id":95, "descripK":"인생이란 네가 다른 계획을 세우느라 바쁠 때 너에게 일어나는 것이다.", "authK":"존 레논",
		"descripE":"Life is what happens to you while you're busy making other plans.", "authE":"John Lennon", "category":"life", "kinda":"c"},
	{ "id":96, "descripK":"왜 굳이 의미를 찾으려 하는가? 인생은 욕망이지, 의미가 아니다.", "authK":"찰리 채플린",
		"descripE":"What do you want a meaning for? Life is a desire, not a meaning", "authE":"Charlie Chaplin", "category":"life"},
	{ "id":97, "descripK":"인생은 자전거를 타는 것과 같다. 균형을 잡으려면 움직여야 한다.", "authK":"알버트 아인슈타인",
		"descripE":"Life is like riding a bicycle. To keep your balance you must keep moving.", "authE":"Albert Einstein", "category":"life"},
	{ "id":98, "descripK":"더욱 거세게 스스로를 다그쳐라", "authK":"게리 바이너척",
		"descripE":"Motivate You to Hustle Harder", "authE":"Gary Vaynerchuk", "category":"success", "kinda":"c"},
	{ "id":99, "descripK":"스킬은 저렴하지만 열정은 값으로 따질 수 없다.", "authK":"게리 바이너척",
		"descripE":"Skills are cheap. Passion is priceless", "authE":"Gary Vaynerchuk", "category":"success", "kinda":"c"},
	{ "id":100, "descripK":"진실은, 매일 하는 일에서 행복을 찾는 것이 절대적으로 긴요하다는 것이다.", "authK":"게리 바이너척",
		"descripE":"The truth is that finding happiness in what you do every day is so imperative", "authE":"Gary Vaynerchuk", "category":"business", "kinda":"c"},
	{ "id":101, "descripK":"오직 남을 위해 산 인생만이 가치 있는 것이다.", "authK":"알버트 아인슈타인",
		"descripE":"Only a life lived for others is a life worth while.", "authE":"Albert Einstein", "category":"love"},
	{ "id":102, "descripK":"나는 폭풍이 두렵지 않다. 나의 배로 항해하는 법을 배우고 있으니까.", "authK":"헬렌 켈러",
		"descripE":"I am not afraid of storms for I am learning how to sail my ship.", "authE":"Helen Keller", "category":"study"},
	{ "id":103, "descripK":"친구를 얻는 방법은 친구에게 부탁을 들어달라고 하는 것이 아니라 내가 부탁을 들어주는 것이다.", "authK":"투키디데스",
		"descripE":"We secure our friends not by accepting favors but by doing them.", "authE":"Thucydides", "category":"friend"},
	{ "id":104, "descripK":"나는 중요한 슛을 놓친 결과에 절대 개의치 않는다. 그 결과에 대해 생각하면 언제나 부정적인 결과만 생각하게 된다.", "authK":"마이클 조던",
		"descripE":"I never looked at the consequences of missing a big shot... when you think about the consequences you always think of a negative result.", "authE":"Michael Jordan", "category":"confidence", "kinda":"c"},
	{ "id":105, "descripK":"거울 속의 자신을 보고 물어보라 남은 생애에 매일 무엇이 하고 싶은 지... 그것을 해라", "authK":"게리 바이너척",
		"descripE":"Look yourself in the mirror and ask yourself, what do i want to do everyday for the rest of my life... do that", "authE":"Gary Vaynerchuk", "category":"success", "kinda":"c"},
	{ "id":106, "descripK":"젊음은 한때 이지만, 철없음은 영원할 수 있다.", "authK":"데이브 배리",
		"descripE":"You can only be young once, But you can always be immature", "authE":"Dave Barry", "category":"life"},
	{ "id":107, "descripK":"강렬한 사랑은 판단하지 않는다. 주기만 할 뿐이다.", "authK":"마더 테레사",
		"descripE":"Intense love does not measure, it just gives.", "authE":"Mother Teresa", "category":"love"},
	{ "id":108, "descripK":"행동의 가치는 그 행동을 끝까지 이루는 데 있다.", "authK":"칭기즈칸",
		"descripE":"The merit of an action lies in finishing it to the end.", "authE":"Genghis Khan", "category":"study"},
	{ "id":109, "descripK":"친구가 어려울 때 돕기는 쉽지만, 당신의 시간을 친구에게 내주는게 항상 시의적절할 수는 없다.", "authK":"찰리 채플린",
		"descripE":"To help a friend in need is easy, but to give him your time is not always opportune.", "authE":"Charlie Chaplin", "category":"friend"},
	{ "id":110, "descripK":"기회 없는 능력은 쓸모가 없다.", "authK":"나폴레옹 보나파르트",
		"descripE":"Ability is of little account without opportunity.", "authE":"Napoleon Bonaparte", "category":"confidence"},
	{ "id":111, "descripK":"영원히 살 것처럼 꿈꾸고 오늘 죽을 것처럼 살아라.", "authK":"제임스 딘",
		"descripE":"Dream as if you'll live forever. Live as if you'll die today.", "authE":"James Dean", "category":"life", "kinda":"c"},
	{ "id":112, "descripK":"9살이든 90살이든 자신이 잘 못 하는 것을 고치려는 짓은 그만하고 자신이 잘하는 것에 집중하라.", "authK":"게리 바이너척",
		"descripE":"Whether you're 9 or 90, stop trying to fix the things you're bad at, and focus on the things you're good at", "authE":"Gary Vaynerchuk", "category":"success", "kinda":"c"},
	{ "id":113, "descripK":"나는 내가 아픔을 느낄만큼 사랑하면 아픔은 사라지고 더 큰 사랑만이 생겨난다는 역설을 발견했다.", "authK":"마더 테레사",
		"descripE":"I have found the paradox that if I love until it hurts, then there is no hurt, but only more love.", "authE":"Mother Teresa", "category":"love"},
	{ "id":114, "descripK":"개인은 천재다. 그러나 군중은 머리없는 괴수, 거대하고 야수같은 바보가 되어 시키는 대로 행동한다.", "authK":"찰리 채플린",
		"descripE":"Man as an individual is a genius. But men in the mass form the headless monster, a great, brutish idiot that goes where prodded.", "authE":"Charlie Chaplin", "category":"study"},
	{ "id":115, "descripK":"들은 것은 잊어버리고, 본 것은 기억하고 직접 해본 것은 이해한다", "authK":"공자",
		"descripE":"I hear and I forget. I see and I remember. I do and I understand.", "authE":"Confucius", "category":"study"},
	{ "id":116, "descripK":"누구에게나 친구는 어느 누구에게도 친구가 아니다.", "authK":"아리스토텔레스",
		"descripE":"A friend to all is a friend to none.", "authE":"Aristotle", "category":"friend"},
	{ "id":117, "descripK":"우리는 가지고 있는 15가지 재능으로 칭찬받으려 하기보다, 가지지도 않은 한가지 재능으로 돋보이려 안달한다.", "authK":"마크 트웨인",
		"descripE":"We are always more anxious to be distinguished for a talent which we do not possess, than to be praised for the fifteen which we do possess.", "authE":"Mark Twain", "category":"confidence"},
	{ "id":118, "descripK":"절대 어제를 후회하지 마라. 인생은 오늘의 나 안에 있고, 내일은 스스로 만드는 것이다.", "authK":"L. 론 허바드",
		"descripE":"Never regret yesterday. Life is in you today, and you make your tommorow.", "authE":"L. Ron Hubbard", "category":"life"},
	{ "id":119, "descripK":"팽귄은 기린이 될 수 없다. 최고의 팽귄이 되라.", "authK":"게리 바이너척",
		"descripE":"A penguin cannot become a giraffe, so just be the best penguin you can be", "authE":"Gary Vaynerchuk", "category":"business", "kinda":"c"},
	{ "id":120, "descripK":"강력한 이유는 강력한 행동을 낳는다.", "authK":"윌리엄 셰익스피어",
		"descripE":"Strong reasons make strong actions.", "authE":"william shakespeare", "category":"study"},
	{ "id":121, "descripK":"매일 이루어지는 거래의 99%는 그리 중요하지 않다. 자신에게 가장 의미가 큰 몇몇 사업 철학을 철저하게 따르면 나머지는 저절로 맞아 떨어진다.", "authK":"게리 바이너척",
		"descripE":"99% of what we deal every day in business doesn't matter. If you religiously follow the few core business philosophies that mean the most to you, everything else will naturally fall into place.", "authE":"Gary Vaynerchuk", "category":"business", "kinda":"c"},
	{ "id":122, "descripK":"능력이 부족할 수록 자만심이 더 강하다.", "authK":"아하드 하암",
		"descripE":"The less their ability, the more their conceit.", "authE":"Ahad HaAm", "category":"confidence"},
	{ "id":123, "descripK":"인생은 사람들 앞에서 바이올린을 켜면서 바이올린을 배우는 것과 같다.", "authK":"사무엘 버틀러",
		"descripE":"Life is like playing a violin in public and learning the instrument as one goes on.", "authE":"Samuel Butler", "category":"life"},
	{ "id":124, "descripK":"당신이 증오하는 쓸모 없는 짓은 그만해라", "authK":"게리 바이너척",
		"descripE":"Stop doing shit you hate", "authE":"Gary Vaynerchuk", "category":"confidence", "kinda":"c"},
	{ "id":125, "descripK":"두 사람이 만나는 것은 두 가지 화학 물질이 접촉하는 것과 같다. 어떤 반응이 일어나면 둘다 완전히 바뀌게 된다.", "authK":"칼 융",
		"descripE":"The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed.", "authE":"Carl Jung", "category":"love"},
	{ "id":126, "descripK":"고대 그리스인들은 능력과 탁월함을 최대한 발휘하는 것을 행복으로 정의했다.", "authK":"존 F. 케네디",
		"descripE":"The ancient Greek definition of happiness was the full use of your powers along lines of excellence.", "authE":"John F. Kennedy", "category":"confidence"},
	{ "id":127, "descripK":"젊음은 알지 못한 것을 탄식하고 나이는 하지 못한 것을 탄식한다.", "authK":"앙리 에스티엔",
		"descripE":"If youth only knew, if age only could", "authE":"Henri Estienne", "category":"life"},
	{ "id":128, "descripK":"투명도가 높아지면, 신뢰도도 높아진다.", "authK":"게리 바이너척",
		"descripE":"Trust is on the rise because transparency is on the rise", "authE":"Gary Vaynerchuk", "category":"business", "kinda":"c"},
	{ "id":129, "descripK":"어떤 생각에 동의하지 않고도 그 생각을 해볼 수 있는 것이 교육받은 사람의 특징이다.", "authK":"아리스토텔레스",
		"descripE":"It is the mark of an educated mind to be able to entertain a thought without accepting it.", "authE":"Aristotle", "category":"study"},
	{ "id":130, "descripK":"모든 사람은 천재성을 갖고 태어나지만, 대부분의 사람은 그것을 단지 몇분간만 유지한다.", "authK":"에드가 바레즈",
		"descripE":"Everyone is born with genius, but most people only keep it a few minutes.", "authE":"Edgard Varese", "category":"confidence"},
	{ "id":131, "descripK":"사랑을 하는 사람과 사랑을 받는 사람은 항상 따로 있어.", "authK":"윌리엄 서머셋, 영국의 소설가",
		"descripE":"There's always one who loves and one who lets himself be loved.", "authE":"William Somerset Maugham", "category":"love"},
	{ "id":132, "descripK":"20대에는 의지, 30대에는 기지, 40대에는 판단이 지배한다.", "authK":"벤자민 프랭클린",
		"descripE":"At 20 years of age the will reigns, at 30 the wit, at 40 the judgment", "authE":"Benjamin Franklin", "category":"life"},
	{ "id":133, "descripK":"우리 모두 가장 신경 쓰이는 한 가지 자산의 지배하에 있다. 그건 시간이다.", "authK":"게리 바이너척",
		"descripE":"We are in control of the one asset that we all give the most f**ks about, and that is time", "authE":"Gary Vaynerchuk", "category":"success", "kinda":"c"}
]