[
	{ "id":1, "descripK":"내가 이해하는 모든 것은 내가 사랑하기 때문에 이해한다.", "authK":"레프 톨스토이", 
		"descripE":"Everything that I understand, I understand only because I love.", "authE":"Lev Tolstoy", "category":"love" },
	{ "id":2, "descripK":"멀리 있는 사람을 사랑하기는 쉽다. 가까이 있는 사람을 사랑하기란 항상 쉬운 것만은 아니다. 기아로부터 사람들을 구제하기 위해서 한 움큼의 쌀을 주는 것이 자신의 집에 있는 이의 외로움과 고통을 덜어주는 것보다 더 쉽다. 당신의 집에 사랑을 가져다 주어라. 가정이야말로 우리의 사랑이 시작되는 곳이어야 하기 때문이다.", "authK":"마더 테레사",
		"descripE":"It is easy to love the people far away. It is not always easy to love those close to us. It is easier to give a cup of rice to relieve hunger than to relieve the loneliness and pain of someone unloved in our home. Bring love into your home for this is where our love for each other must start.", "authE":"Mother Teresa", "category":"love"},
	{ "id":3, "descripK":"사랑에 의해 행해지는 것은 언제나 선악을 초월한다.", "authK":"프레드리히 나체",
		"descripE":"What is done out of love always takes place beyond good and evil.", "authE":"Friedrich Nietzsche", "category":"love"},
	{ "id":4, "descripK":"겁쟁이는 사랑을 드러낼 능력이 없다. 사랑은 용기있는 자의 특권이다.", "authK":"마하트마 간디",
		"descripE":"A coward is incapable of exhibiting love, it is the prerogative of the brave.", "authE":"Mahatma Gandhi", "category":"love"},
	{ "id":5, "descripK":"사랑은 눈으로 보지 않고 마음으로 보는 거지.", "authK":"윌리엄 셰익스피어",
		"descripE":"Love looks not with the eyes, but with the mind.", "authE":"William Shakespeare", "category":"love"},
	{ "id":6, "descripK":"나는 젊음이요, 나는 기쁨이요, 나는 알에서 갓 깬 작은 새다.", "authK":"제임스 M. 배리",
		"descripE":"I'm youth, I'm joy, I'm a little bird that has broken out of the egg.", "authE":"James M. Barrie", "category":"life"},
	{ "id":7, "descripK":"젊음은 매우 새로운 것이다. 20년 전에는 아무도 이것을 언급하지 않았다.", "authK":"가브리엘(코코)샤넬",
		"descripE":"Youth is something very new: twenty years ago no one mentioned it.", "authE":"Gabriel Coco Chanel", "category":"life"},
	{ "id":8, "descripK":"인간사에는 안정된 것이 하나도 없음을 기억하라. 그러므로 성공에 들뜨거나 역경에 지나치게 의기소침하지 마라.", "authK":"소크라테스",
		"descripE":"Remember that there is nothing stable in human affairs; therefore avoid undue elation in prosperity, or undue depression in adversity.", "authE":"Socrates", "category":"life"},
	{ "id":9, "descripK":"자기 새끼를 잡아먹기 좋아하는 담수어를 제외하고 인간은 일부러 아이를 가지는 유일한 동물이다.", "authK":"P. J. 오루크",
		"descripE":"Humans are the only animals that have children on purpose with the exception of guppies, who like to eat theirs.", "authE":"P. J. O'Rourke", "category":"life"},
	{ "id":10, "descripK":"진정한 여행자는 걸어서 다니는 자이며, 걸으면서도 자주 앉는다.", "authK":"콜레트",
		"descripE":"The true traveler is he who goes on foot, and even then, he sits down a lot of the time", "authE":"Colette", "category":"life"},
	{ "id":11, "descripK":"제대로 배우기 위해서는 거창하고 교양 있는 전통이나 돈이 필요하지 않다. 스스로를 개선하고자 하는 열망이 있는 사람들이 필요할 뿐이다.", "authK":"아담 쿠퍼",
		"descripE":"You don't need fancy highbrow traditions or money to really learn. You just need people with the desire to better themselves.", "authE":"Adam Cooper", "category":"study"},
	{ "id":12, "descripK":"어려운 직업에서 성공하려면 자신을 굳게 믿어야 한다. 이것이 탁월한 재능을 지닌 사람보다 재능은 평범하지만 강한 투지를 가진 사람이 훨씬 더 성공하는 이유다.", "authK":"소피아 로렌",
		"descripE":"Getting ahead in a difficult profession requires avid faith in yourself. That is why some people with mediocre talent, but with great inner drive, go much further than people with vastly superior talent.", "authE":"Sophia Loren", "category":"study"},
	{ "id":13, "descripK":"아이들이 답이 있는 질문을 하기 시작하면 그들이 성장하고 있음을 알 수 있다.", "authK":"존 J. 플롬프",
		"descripE":"You know that children are growing up when they start asking questions that have answers.", "authE":"John J. Plomp", "category":"study"},
	{ "id":14, "descripK":"인생에서 가장 위대한 교훈은, 심지어는 바보도 어떨 때는 옳다는 걸 아는 것이다.", "authK":"윈스턴 처칠",
		"descripE":"The greatest lesson in life is to know that even fools are right sometimes.", "authE":"Sir Winston Churchill", "category":"study"},
	{ "id":15, "descripK":"함께 있는 사람들보다 학식이 높아 보이지 말라. 당신의 학식을 회중시계마냥 주머니 속에 감춰라. 단지 시간을 세기 위해 시계를 꺼내지 말되 누군가가 시간을 물어보면 알려줘라.", "authK":"체스터필드 경",
		"descripE":"Never seem more learned than the people you are with. Wear your learning like a pocket watch and keep it hidden. Do not pull it out to count the hours, but give the time when you are asked.", "authE":"Lord Chesterfield", "category":"study"},
	{ "id":16, "descripK":"인간은 운명의 포로가 아니라 단지 자기 마음의 포로일 뿐이다.", "authK":"프랭클린 D. 루스벨트",
		"descripE":"Men are not prisoners of fate, but only prisoners of their own minds.", "authE":"Franklin D. Roosevelt", "category":"success"},
	{ "id":17, "descripK":"새로운 것의 창조는 지능이 아니라 내적 필요에 의한 놀기 본능을 통해 달성된다. 창의적인 사람은 자신이 사랑하는 것을 가지고 놀기 좋아한다.", "authK":"칼 융",
		"descripE":"The creation of something new is not accomplished by the intellect but by the play instinct acting from inner necessity. The creative mind plays with the objects it loves.", "authE":"Carl Jung", "category":"success"},
	{ "id":18, "descripK":"기회가 찾아오는 정확한 때와 장소를 알아보고 그 기회를 잡을 수 있어야 한다. 세상에 기회는 많다. 그저 손 놓고 앉아 있을 수는 없다.", "authK":"엘렌 멧칼프",
		"descripE":"You have to recognize when the right place and the right time fuse and take advantage of that opportunity. There are plenty of opportunities out there. You can't sit back and wait.", "authE":"Ellen Metcalf", "category":"success"},
	{ "id":19, "descripK":"우리가 어떤 형태로든 '될대로 되라지!'라고 할 때 마다 무슨 일이 생긴다.", "authK":"스텔라 테릴 만",
		"descripE":"Every time we say, 'Let there be!' in any form, something happens.", "authE":"Stella Terrill Mann", "category":"success"},
	{ "id":20, "descripK":"남에게 이기는 방법의 하나는 예의범절로 이기는 것이다.", "authK":"조쉬 빌링스",
		"descripE":"One of the greatest victories you can gain over someone is to beat him at politeness.", "authE":"Josh Billings", "category":"success"},
	{ "id":21, "descripK":"친구라면 친구의 결점을 참고 견뎌야 한다.", "authK":"윌리엄 셰익스피어",
		"descripE":"A friend should bear his friend's infirmities.", "authE":"William Shakespeare", "category":"friend"},
	{ "id":22, "descripK":"친구는 모든 것을 나눈다.", "authK":"플라톤",
		"descripE":"Friends have all things in common.", "authE":"Plato", "category":"friend"},
	{ "id":23, "descripK":"친구의 충고는 신중하게 곱씹어 받아들여야 한다. 옳건 그르건, 자신의 생각을 포기하고 친구의 충고를 무조건 따라서는 안된다.", "authK":"피에르 샤롱",
		"descripE":"The advice of friends must be received with a judicious reserve, we must not give ourselves up to it and follow it blindly, whether right or wrong.", "authE":"Pierre Charron", "category":"friend"},
	{ "id":24, "descripK":"아첨꾼은 나보다 열등하거나 그런 척 하는 친구이다.", "authK":"아리스토텔레스",
		"descripE":"A flatterer is a friend who is your inferior, or pretends to be so.", "authE":"Aristotle", "category":"friend"},
	{ "id":25, "descripK":"운명의 기복은 친구의 신뢰를 시험한다.", "authK":"키케로",
		"descripE":"The shifts of Fortune test the reliability of friends.", "authE":"Cicero", "category":"friend"},
	{ "id":26, "descripK":"좋은 책을 읽는 것은 과거 몇 세기의 가장 훌륭한 사람들과 이야기를 나누는 것과 같다.", "authK":"르네 데카르트",
		"descripE":"The reading of all good books is like a conversation with the finest men of past centuries.", "authE":"Rene Descartes", "category":"book"},
	{ "id":27, "descripK":"읽는 것 만큼 쓰는 것을 통해서도 많이 배운다.", "authK":"액톤 경",
		"descripE":"Learn as much by writing as by reading.", "authE":"Lord Acton", "category":"book"},
	{ "id":28, "descripK":"부당하게 잊혀지는 책은 있어도 과분하게 기억되는 책은 없다.", "authK":"오든",
		"descripE":"Some books are undeservedly forgotten, none are undeservedly remembered.", "authE":"W. H. Auden", "category":"book"},
	{ "id":29, "descripK":"낡은 외투를 그냥 입고 새 책을 사라.", "authK":"오스틴 펠프스",
		"descripE":"Wear the old coat and buy the new book.", "authE":"Austin Phelps", "category":"book"},
	{ "id":30, "descripK":"나는 삶을 변화시키는 아이디어를 항상 책에서 얻었다.", "authK":"벨 훅스",
		"descripE":"Life-transforming ideas have always come to me through books.", "authE":"Bell Hooks", "category":"book"}
]